log messages to file: C:\Python38-32\Lib\site-packages\natlinkcore\PyTest\testresult.txt
starting unittestNatlink

starting tests with threading: 0

test recognitionMimicCommands, version: 15
validLists: ['colors', 'qualification']

--------------- errors -----------------

--------------- failures -----------------

---------- testRecognitionMimicCommands (__main__.UnittestNatlink) --------
Traceback (most recent call last):
  File "<string>", line 1700, in doTestCommandRecognition
natlink.MimicFailed: recognitionMimic call failed (The speech engine returned the following error: MimicNoResults)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1101, in testRecognitionMimicCommands
  File "<string>", line 1704, in doTestCommandRecognition
AssertionError: ===test failed: MimicFailed, but expected 1 (words: ['mimicss', 'runone', 'north'])
